using System.Diagnostics; using System.IO; using System.Windows; using System.Windows.Threading; using Forms=System.Windows.Forms; using OrynoSync.Core;
namespace OrynoSync.App;
public partial class MainWindow : Window
{
 private readonly ILocalStateStore _store; private readonly MockSyncApi _api=new(){Online=false}; private readonly string _dbPath=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Oryno Sync","oryno-sync.db"); private string? _root; private SyncEngine? _engine; private LocalWatcher? _watcher; private Forms.NotifyIcon? _tray; private bool _allowClose; private readonly List<ActivityEntry> _activities=[];
 public MainWindow(){InitializeComponent();_store=new SqliteLocalStateStore(_dbPath);Loaded+=LoadedAsync;var timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(500)};timer.Tick+=(_,_)=>{if(App.ActivateEvent.WaitOne(0))ShowFromTray();};timer.Start();}
 private async void LoadedAsync(object? s,RoutedEventArgs e){await _store.InitializeAsync();_root=await _store.GetSettingAsync("sync_root");if(string.IsNullOrWhiteSpace(_root))_root=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"Oryno NAS");FolderText.Text=_root;SetupTray();await StartEngineAsync();}
 private async Task StartEngineAsync(){if(_root is null)return;var ignore=new IgnoreRules();var processor=new DebouncedChangeProcessor(_store,_root,ignore,new LocalMutationSuppression());processor.Activity+=AddActivity;_watcher=new LocalWatcher(_root,processor);_watcher.Overflowed+=async()=>await new LocalReconciler(_store,ignore).ScanAsync(_root);if(Directory.Exists(_root))_watcher.Start();_engine=new SyncEngine(_store,_api,_root);_engine.StateChanged+=s=>Dispatcher.Invoke(()=>SetState(s));_engine.Activity+=AddActivity;await new LocalReconciler(_store,ignore).ScanAsync(_root);_ = QueueLoopAsync();}
 private async Task QueueLoopAsync(){while(!_allowClose){if(_engine is not null)await _engine.ProcessQueueAsync();if(IsVisible)await Dispatcher.InvokeAsync(async()=>QueueText.Text=$"{await _store.PendingCountAsync()} pending");await Task.Delay(TimeSpan.FromSeconds(3));}}
 private void SetState(EngineState s){SidebarStatus.Text=s.ToString();StatusText.Text=s switch{EngineState.UpToDate=>"✓ Everything is up to date",EngineState.Syncing=>"↻ Syncing local changes",EngineState.Paused=>"Ⅱ Syncing paused",_=>"○ Offline  ·  Changes will sync when Oryno NAS is available"};}
 private void AddActivity(ActivityEntry a){Dispatcher.Invoke(()=>{_activities.Insert(0,a);if(_activities.Count>1000)_activities.RemoveAt(1000);ActivityList.ItemsSource=null;ActivityList.ItemsSource=_activities.Select(x=>$"{(x.Status=="Synced"?"✓":"↻")}  {x.RelativePath}   {x.Status}").ToArray();});}
 private void SetupTray(){_tray=new Forms.NotifyIcon{Icon=System.Drawing.SystemIcons.Application,Text="Oryno Sync",Visible=true};var menu=new Forms.ContextMenuStrip();menu.Items.Add("Oryno Sync");menu.Items.Add("Open Oryno NAS Folder",null,(_,_)=>OpenFolder_Click(null,null));menu.Items.Add("Open Oryno Sync",null,(_,_)=>ShowFromTray());menu.Items.Add("Pause Syncing",null,(_,_)=>Pause_Click(null,null));menu.Items.Add("Exit",null,(_,_)=>{_allowClose=true;Close();});_tray.ContextMenuStrip=menu;_tray.DoubleClick+=(_,_)=>ShowFromTray();}
 private void ShowFromTray(){Show();WindowState=WindowState.Normal;Activate();} private async void ChooseFolder_Click(object? s,RoutedEventArgs? e){using var d=new Forms.FolderBrowserDialog{Description="Choose Oryno Sync folder",SelectedPath=_root??string.Empty};if(d.ShowDialog()==Forms.DialogResult.OK){_root=d.SelectedPath;FolderText.Text=_root;await _store.SaveSettingAsync("sync_root",_root);}}
 private void OpenFolder_Click(object? s,RoutedEventArgs? e){if(_root is not null&&Directory.Exists(_root))Process.Start(new ProcessStartInfo("explorer.exe",_root){UseShellExecute=true});} private void Pause_Click(object? s,RoutedEventArgs? e){if(_engine is null)return;if(_engine.IsPaused){_engine.Resume();PauseButton.Content="Pause syncing";}else{_engine.Pause();PauseButton.Content="Resume syncing";}}
 private void Activity_Click(object? s,RoutedEventArgs? e){PageTitle.Text="Activity";}private void Folders_Click(object? s,RoutedEventArgs? e){PageTitle.Text="Folders";}private void Settings_Click(object? s,RoutedEventArgs? e){WindowsAutostart.Set(!WindowsAutostart.Enabled);PageTitle.Text=$"Settings · Start at sign-in {(WindowsAutostart.Enabled?"on":"off")}";}private void Window_Closing(object? s,System.ComponentModel.CancelEventArgs e){if(!_allowClose){e.Cancel=true;Hide();}else{_watcher?.Dispose();_tray?.Dispose();}}
}
