using System.Diagnostics;
using System.IO;
using System.Net.Http;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Threading;
using Forms=System.Windows.Forms;
using OrynoSync.Core;

namespace OrynoSync.App;

public partial class MainWindow : Window
{
    private readonly string _appData=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Oryno Sync");
    private readonly ILocalStateStore _store;private readonly IRemoteStateStore _remoteStore;private readonly ICredentialStore _credentials;
    private readonly List<string> _activity=[];private LocalWatcher? _watcher;private CancellationTokenSource? _localCts;private CancellationTokenSource? _remoteCts;private HttpClient? _http;private OrynoNasSyncApi? _api;private MetadataSyncCoordinator? _metadata;private Forms.NotifyIcon? _tray;private string? _root;private Guid? _selectedRootId;private bool _paused;private bool _allowClose;private int _failures;
    private string DatabasePath=>Path.Combine(_appData,"oryno-sync.db");
    public MainWindow()
    {
        InitializeComponent();_store=new SqliteLocalStateStore(DatabasePath);_remoteStore=new RemoteStateStore(DatabasePath);_credentials=new WindowsCredentialStore(Path.Combine(_appData,"Credentials"));Loaded+=LoadedAsync;var timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(500)};timer.Tick+=(_,_)=>{if(App.ActivateEvent.WaitOne(0))ShowFromTray();};timer.Start();
    }
    private async void LoadedAsync(object? sender,RoutedEventArgs e)
    {
        await _store.InitializeAsync();await _remoteStore.InitializeAsync();SetupTray();DeviceText.Text=Environment.MachineName+" · Windows";ServerUrlBox.Text=await _store.GetSettingAsync("server_url")??"https://oryno-nas.remo78.ru";_root=await _store.GetSettingAsync("sync_root")??Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"Oryno NAS");FolderText.Text=_root;var rootSetting=await _store.GetSettingAsync("selected_root_id");if(Guid.TryParse(rootSetting,out var rootId))_selectedRootId=rootId;if(Directory.Exists(_root))await StartLocalAsync(_root);else SetStatus(EngineState.Offline,"Choose an existing local sync folder. No folder was created automatically.");InitializeProductionClient();_remoteCts=new CancellationTokenSource();_=RemoteLoopAsync(_remoteCts.Token);await RefreshCountersAsync();
    }
    private string CredentialAccount(Uri uri)=>$"oryno-sync:{uri.Scheme}://{uri.Host}:{uri.Port}";
    private void InitializeProductionClient()
    {
        _http?.Dispose();if(!TryServerUri(out var uri))return;var handler=new BearerTokenHandler(ct=>_credentials.ReadAsync(CredentialAccount(uri),ct)){InnerHandler=new SocketsHttpHandler{ConnectTimeout=TimeSpan.FromSeconds(8),PooledConnectionLifetime=TimeSpan.FromMinutes(10)}};_http=new HttpClient(handler);_api=new OrynoNasSyncApi(_http,uri);_metadata=new MetadataSyncCoordinator(_api,_remoteStore);_metadata.Progress+=p=>Dispatcher.Invoke(()=>{SetStatus(p.State,p.Message);if(p.Revision>0)RevisionText.Text=p.Revision.ToString("N0");});
    }
    private bool TryServerUri(out Uri uri){if(Uri.TryCreate(ServerUrlBox.Text.Trim(),UriKind.Absolute,out var parsed)&&parsed.Scheme==Uri.UriSchemeHttps){uri=parsed;return true;}uri=null!;SetStatus(EngineState.ProtocolError,"Production server URL must use HTTPS.");return false;}
    private async Task StartLocalAsync(string root)
    {
        _watcher?.Dispose();_localCts?.Cancel();_localCts?.Dispose();_localCts=new CancellationTokenSource();var ignore=new IgnoreRules();var processor=new DebouncedChangeProcessor(_store,root,ignore,new LocalMutationSuppression());processor.Activity+=a=>AddActivity($"{a.RelativePath} · Local {a.Action} · Waiting to upload");_watcher=new LocalWatcher(root,processor);_watcher.Overflowed+=()=>_ = Task.Run(()=>new LocalReconciler(_store,ignore).ScanAsync(root,_localCts.Token));await Task.Run(()=>new LocalReconciler(_store,ignore).ScanAsync(root,_localCts.Token));_watcher.Start();
    }
    private async Task RemoteLoopAsync(CancellationToken ct)
    {
        while(!ct.IsCancellationRequested){if(_paused){await Delay(1000,ct);continue;}try{if(_api is null||_metadata is null){await Delay(4000,ct);continue;}var connection=await _api.TestConnectionAsync(ct);if(connection.Status!=ConnectionStatus.Connected){SetConnection(connection);_failures++;await Delay(BackoffMs(),ct);continue;}_failures=0;SetStatus(EngineState.Connecting,"Connected. Reading sync roots…");var roots=await _metadata.GetRootsAsync(ct);await Dispatcher.InvokeAsync(()=>PopulateRoots(roots));if(_selectedRootId is Guid root){await _metadata.RunCycleAsync(root,ct);await RefreshRemoteAsync(root,ct);}else SetStatus(EngineState.OnlineIdle,roots.Count==0?"No sync folders are configured on Oryno NAS.":"Select an Oryno NAS sync root.");await RefreshCountersAsync();await Delay(4000,ct);}catch(OperationCanceledException)when(ct.IsCancellationRequested){break;}catch(SyncApiException ex)when(ex.Status==System.Net.HttpStatusCode.Unauthorized){SetStatus(EngineState.AuthenticationRequired,"Oryno NAS authorization is required. Your local changes are safe.");_failures++;await Delay(BackoffMs(),ct);}catch(Exception ex){SetStatus(EngineState.Offline,"Server unavailable. Local changes remain queued.");AddActivity($"Connection error · {SafeError(ex)}");_failures++;await Delay(BackoffMs(),ct);}}
    }
    private int BackoffMs()=>Math.Min(60000,(int)(2000*Math.Pow(2,Math.Min(_failures,5))));private static async Task Delay(int ms,CancellationToken ct){try{await Task.Delay(ms,ct);}catch(OperationCanceledException){}}
    private void PopulateRoots(IReadOnlyList<SyncRootDto> roots){var current=_selectedRootId;RootSelector.ItemsSource=roots.Where(x=>x.Enabled).ToArray();if(current is Guid id)RootSelector.SelectedItem=roots.FirstOrDefault(x=>x.RootId==id);else if(roots.Count(x=>x.Enabled)==1)RootSelector.SelectedItem=roots.First(x=>x.Enabled);}
    private async Task RefreshRemoteAsync(Guid rootId,CancellationToken ct){var state=await _remoteStore.GetRootStateAsync(rootId,ct);var count=await _remoteStore.CountRemoteItemsAsync(rootId,ct);var downloads=await _remoteStore.CountPlanningAsync(rootId,RemotePlanningState.NeedsDownload,ct);await Dispatcher.InvokeAsync(()=>{RevisionText.Text=state.LastRevision.ToString("N0");RemoteCountText.Text=$"{count:N0} items";TransferNotice.Text=downloads==0?"Metadata current. Content transfer requires server S.2.":$"{downloads:N0} files waiting for content sync support.";});}
    private async Task RefreshCountersAsync(){var count=await _store.PendingCountAsync();await Dispatcher.InvokeAsync(()=>QueueText.Text=$"{count:N0} local changes waiting");}
    private void SetConnection(ConnectionResult result){var state=result.Status switch{ConnectionStatus.AuthenticationRequired or ConnectionStatus.AuthenticationRevoked=>EngineState.AuthenticationRequired,ConnectionStatus.ProtocolError or ConnectionStatus.TlsError=>EngineState.ProtocolError,_=>EngineState.Offline};var message=result.Status switch{ConnectionStatus.AuthenticationRequired=>"Server reachable — device authorization required.",ConnectionStatus.AuthenticationRevoked=>"Device authorization was revoked. Local changes are safe.",ConnectionStatus.TlsError=>"TLS certificate or handshake error.",ConnectionStatus.ProtocolError=>"Server reached, but the Sync protocol response is invalid.",_=>"Server unavailable. Local changes continue to queue."};SetStatus(state,message);}
    private void SetStatus(EngineState state,string message)=>Dispatcher.Invoke(()=>{SidebarStatus.Text=state.ToString();StatusText.Text=message;_tray!.Text=("Oryno Sync — "+state).Substring(0,Math.Min(63,("Oryno Sync — "+state).Length));});
    private void AddActivity(string text)=>Dispatcher.Invoke(()=>{_activity.Insert(0,$"{DateTime.Now:t}  {text}");if(_activity.Count>1000)_activity.RemoveAt(1000);ActivityList.ItemsSource=null;ActivityList.ItemsSource=_activity;});
    private static string SafeError(Exception ex)=>ex is SyncApiException api?$"{api.Code} ({(int)api.Status})":ex.GetType().Name;
    private async void Connect_Click(object sender,RoutedEventArgs e)
    {
        if(!TryServerUri(out var uri))return;var token=TokenBox.Password.Trim();if(string.IsNullOrWhiteSpace(token)){SetStatus(EngineState.AuthenticationRequired,"Enter the one-time device authorization token issued by Oryno NAS.");return;}SetStatus(EngineState.Connecting,"Testing device authorization…");using var tempHttp=new HttpClient(new BearerTokenHandler(_=>Task.FromResult<string?>(token)){InnerHandler=new SocketsHttpHandler{ConnectTimeout=TimeSpan.FromSeconds(8)}});var tempApi=new OrynoNasSyncApi(tempHttp,uri);var result=await tempApi.TestConnectionAsync();if(result.Status!=ConnectionStatus.Connected){SetConnection(result);return;}var old=await _store.GetSettingAsync("server_url");if(!string.Equals(old,uri.GetLeftPart(UriPartial.Authority),StringComparison.OrdinalIgnoreCase)){_selectedRootId=null;await _store.SaveSettingAsync("selected_root_id",string.Empty);}await _credentials.SaveAsync(CredentialAccount(uri),token);await _store.SaveSettingAsync("server_url",uri.GetLeftPart(UriPartial.Authority));TokenBox.Clear();ServerUrlBox.Text=uri.GetLeftPart(UriPartial.Authority);InitializeProductionClient();RestartRemoteLoop();SetStatus(EngineState.Connecting,"Device authorized. Loading roots…");
    }
    private async void TestConnection_Click(object sender,RoutedEventArgs e){if(_api is null)InitializeProductionClient();if(_api is null)return;SetConnection(await _api.TestConnectionAsync());}
    private async void RootSelector_SelectionChanged(object sender,SelectionChangedEventArgs e){if(RootSelector.SelectedItem is not SyncRootDto root||root.RootId==_selectedRootId)return;_selectedRootId=root.RootId;await _store.SaveSettingAsync("selected_root_id",root.RootId.ToString());RestartRemoteLoop();AddActivity($"Sync root selected · {root.Name}");}
    private async void ChooseFolder_Click(object sender,RoutedEventArgs e){using var dialog=new Forms.FolderBrowserDialog{Description="Choose an existing Oryno Sync folder",SelectedPath=_root??string.Empty};if(dialog.ShowDialog()!=Forms.DialogResult.OK)return;_paused=true;_watcher?.Dispose();_localCts?.Cancel();_root=dialog.SelectedPath;await _store.SaveSettingAsync("sync_root",_root);FolderText.Text=_root;await StartLocalAsync(_root);_paused=false;RestartRemoteLoop();AddActivity($"Local folder changed · {_root}");}
    private void RestartRemoteLoop(){_remoteCts?.Cancel();_remoteCts?.Dispose();_remoteCts=new CancellationTokenSource();_failures=0;_=RemoteLoopAsync(_remoteCts.Token);}
    private void Pause_Click(object sender,RoutedEventArgs e){_paused=!_paused;PauseButton.Content=_paused?"Resume syncing":"Pause syncing";SetStatus(_paused?EngineState.Paused:EngineState.Connecting,_paused?"Metadata transfers paused. Local watcher remains active.":"Resuming metadata connection…");if(!_paused)RestartRemoteLoop();}
    private void OpenFolder_Click(object? sender,RoutedEventArgs? e){if(_root is not null&&Directory.Exists(_root))Process.Start(new ProcessStartInfo("explorer.exe",_root){UseShellExecute=true});}
    private void SetupTray(){_tray=new Forms.NotifyIcon{Icon=System.Drawing.SystemIcons.Application,Text="Oryno Sync",Visible=true};var menu=new Forms.ContextMenuStrip();menu.Items.Add("Oryno Sync");menu.Items.Add("Open Oryno NAS Folder",null,(_,_)=>OpenFolder_Click(null,null));menu.Items.Add("Open Oryno Sync",null,(_,_)=>ShowFromTray());menu.Items.Add("Pause Syncing",null,(_,_)=>Pause_Click(this,new RoutedEventArgs()));menu.Items.Add("Exit",null,(_,_)=>{_allowClose=true;Close();});_tray.ContextMenuStrip=menu;_tray.DoubleClick+=(_,_)=>ShowFromTray();}
    private void ShowFromTray(){Show();WindowState=WindowState.Normal;Activate();}private void Window_Closing(object? sender,System.ComponentModel.CancelEventArgs e){if(!_allowClose){e.Cancel=true;Hide();return;}_remoteCts?.Cancel();_localCts?.Cancel();_watcher?.Dispose();_http?.Dispose();_tray?.Dispose();Dispatcher.BeginInvoke(()=>System.Windows.Application.Current.Shutdown());}
    private void Window_SizeChanged(object sender,SizeChangedEventArgs e){var narrow=ActualWidth<650;NavColumn.Width=narrow?new GridLength(0):new GridLength(190);Sidebar.Visibility=narrow?Visibility.Collapsed:Visibility.Visible;CompactMenu.Visibility=narrow?Visibility.Visible:Visibility.Collapsed;}
    private void CompactMenu_Click(object sender,RoutedEventArgs e){ConnectionPanel.BringIntoView();}private void Activity_Click(object sender,RoutedEventArgs e){PageTitle.Text="Activity";}private void Folders_Click(object sender,RoutedEventArgs e){PageTitle.Text="Folders";}private void Settings_Click(object sender,RoutedEventArgs e){PageTitle.Text="Settings";ConnectionPanel.BringIntoView();}
}
