using Microsoft.Data.Sqlite;
namespace OrynoSync.Core;
public sealed class SqliteLocalStateStore(string databasePath) : ILocalStateStore
{
    private readonly string _cs = new SqliteConnectionStringBuilder { DataSource = databasePath, Mode = SqliteOpenMode.ReadWriteCreate, Cache = SqliteCacheMode.Shared }.ToString();
    private SqliteConnection Open() { var c = new SqliteConnection(_cs); c.Open(); return c; }
    public async Task InitializeAsync(CancellationToken ct=default) { Directory.CreateDirectory(Path.GetDirectoryName(databasePath)!); await using var c=Open(); await using var cmd=c.CreateCommand(); cmd.CommandText="CREATE TABLE IF NOT EXISTS local_items(local_id TEXT PRIMARY KEY,server_item_id TEXT,relative_path TEXT UNIQUE NOT NULL,item_type TEXT NOT NULL,size INTEGER NOT NULL,mtime TEXT NOT NULL,content_hash TEXT,server_version INTEGER,last_server_revision INTEGER,sync_state TEXT NOT NULL,last_error TEXT);CREATE TABLE IF NOT EXISTS pending_operations(operation_id TEXT PRIMARY KEY,operation_type TEXT NOT NULL,relative_path TEXT NOT NULL,secondary_path TEXT,created_at TEXT NOT NULL,attempt_count INTEGER NOT NULL,next_attempt_at TEXT NOT NULL,state TEXT NOT NULL,last_error TEXT);CREATE TABLE IF NOT EXISTS sync_state(key TEXT PRIMARY KEY,value TEXT);CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);"; await cmd.ExecuteNonQueryAsync(ct); }
    private static LocalItem ReadItem(SqliteDataReader r)=>new(r.GetString(0),Enum.Parse<ItemType>(r.GetString(1)),r.GetInt64(2),DateTimeOffset.Parse(r.GetString(3)),r.IsDBNull(4)?null:r.GetString(4),r.IsDBNull(5)?null:r.GetString(5),r.IsDBNull(6)?null:r.GetInt64(6),r.IsDBNull(7)?null:r.GetInt64(7),Enum.Parse<SyncItemState>(r.GetString(8)),r.IsDBNull(9)?null:r.GetString(9));
    private static void Add(SqliteParameterCollection p,string n,object? v)=>p.AddWithValue(n,v??DBNull.Value);
    public async Task<IReadOnlyList<LocalItem>> GetItemsAsync(CancellationToken ct=default){await using var c=Open();await using var cmd=c.CreateCommand("SELECT relative_path,item_type,size,mtime,content_hash,server_item_id,server_version,last_server_revision,sync_state,last_error FROM local_items");await using var r=await cmd.ExecuteReaderAsync(ct);var a=new List<LocalItem>();while(await r.ReadAsync(ct))a.Add(ReadItem(r));return a;}
    public async Task<LocalItem?> GetItemAsync(string path,CancellationToken ct=default){await using var c=Open();await using var cmd=c.CreateCommand("SELECT relative_path,item_type,size,mtime,content_hash,server_item_id,server_version,last_server_revision,sync_state,last_error FROM local_items WHERE relative_path=$p");Add(cmd.Parameters,"$p",PathRules.NormalizeRelative(path));await using var r=await cmd.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?ReadItem(r):null;}
    public async Task UpsertItemAsync(LocalItem i,CancellationToken ct=default){await using var c=Open();await using var cmd=c.CreateCommand("INSERT INTO local_items(local_id,server_item_id,relative_path,item_type,size,mtime,content_hash,server_version,last_server_revision,sync_state,last_error) VALUES($id,$sid,$p,$t,$s,$m,$h,$v,$r,$st,$e) ON CONFLICT(relative_path) DO UPDATE SET size=$s,mtime=$m,content_hash=$h,sync_state=$st,last_error=$e,server_item_id=$sid,server_version=$v,last_server_revision=$r");Add(cmd.Parameters,"$id",Guid.NewGuid().ToString());Add(cmd.Parameters,"$sid",i.ServerItemId);Add(cmd.Parameters,"$p",i.RelativePath);Add(cmd.Parameters,"$t",i.ItemType.ToString());Add(cmd.Parameters,"$s",i.Size);Add(cmd.Parameters,"$m",i.Mtime.ToString("O"));Add(cmd.Parameters,"$h",i.ContentHash);Add(cmd.Parameters,"$v",i.ServerVersion);Add(cmd.Parameters,"$r",i.LastServerRevision);Add(cmd.Parameters,"$st",i.SyncState.ToString());Add(cmd.Parameters,"$e",i.LastError);await cmd.ExecuteNonQueryAsync(ct);}
    public async Task RemoveItemAsync(string p,CancellationToken ct=default){await using var c=Open();await using var cmd=c.CreateCommand("DELETE FROM local_items WHERE relative_path=$p");Add(cmd.Parameters,"$p",PathRules.NormalizeRelative(p));await cmd.ExecuteNonQueryAsync(ct);}
    public async Task EnqueueAsync(PendingOperation o,CancellationToken ct=default){await using var c=Open();await using var tx=c.BeginTransaction();await using var find=c.CreateCommand("SELECT operation_id,operation_type FROM pending_operations WHERE relative_path=$p AND state IN ('Pending','Failed') ORDER BY created_at DESC LIMIT 1");find.Transaction=tx;Add(find.Parameters,"$p",o.RelativePath);var old=await find.ExecuteScalarAsync(ct);await using var cmd=c.CreateCommand();cmd.Transaction=tx;if(old is not null && o.Type!=OperationType.Move){cmd.CommandText="UPDATE pending_operations SET operation_type=$t,secondary_path=$sp,created_at=$c,next_attempt_at=$n,state='Pending',last_error=NULL WHERE operation_id=$id";Add(cmd.Parameters,"$id",old);Add(cmd.Parameters,"$t",o.Type.ToString());Add(cmd.Parameters,"$sp",o.SecondaryPath);Add(cmd.Parameters,"$c",(o.CreatedAt??DateTimeOffset.UtcNow).ToString("O"));Add(cmd.Parameters,"$n",(o.NextAttemptAt??DateTimeOffset.UtcNow).ToString("O"));}else{cmd.CommandText="INSERT INTO pending_operations VALUES($id,$t,$p,$sp,$c,$a,$n,$s,$e)";Add(cmd.Parameters,"$id",o.OperationId.ToString());Add(cmd.Parameters,"$t",o.Type.ToString());Add(cmd.Parameters,"$p",o.RelativePath);Add(cmd.Parameters,"$sp",o.SecondaryPath);Add(cmd.Parameters,"$c",(o.CreatedAt??DateTimeOffset.UtcNow).ToString("O"));Add(cmd.Parameters,"$a",o.AttemptCount);Add(cmd.Parameters,"$n",(o.NextAttemptAt??DateTimeOffset.UtcNow).ToString("O"));Add(cmd.Parameters,"$s",o.State.ToString());Add(cmd.Parameters,"$e",o.LastError);}await cmd.ExecuteNonQueryAsync(ct);await tx.CommitAsync(ct);}
    public async Task<IReadOnlyList<PendingOperation>> GetPendingAsync(DateTimeOffset now,CancellationToken ct=default){await using var c=Open();await using var cmd=c.CreateCommand("SELECT operation_id,operation_type,relative_path,secondary_path,created_at,attempt_count,next_attempt_at,state,last_error FROM pending_operations WHERE state IN ('Pending','Failed') AND next_attempt_at <= $n ORDER BY created_at");Add(cmd.Parameters,"$n",now.ToString("O"));await using var r=await cmd.ExecuteReaderAsync(ct);var a=new List<PendingOperation>();while(await r.ReadAsync(ct))a.Add(new(Guid.Parse(r.GetString(0)),Enum.Parse<OperationType>(r.GetString(1)),r.GetString(2),r.IsDBNull(3)?null:r.GetString(3),DateTimeOffset.Parse(r.GetString(4)),r.GetInt32(5),DateTimeOffset.Parse(r.GetString(6)),Enum.Parse<OperationState>(r.GetString(7)),r.IsDBNull(8)?null:r.GetString(8)));return a;}
    public async Task UpdateOperationAsync(PendingOperation o,CancellationToken ct=default){await using var c=Open();await using var cmd=c.CreateCommand("UPDATE pending_operations SET attempt_count=$a,next_attempt_at=$n,state=$s,last_error=$e WHERE operation_id=$id");Add(cmd.Parameters,"$id",o.OperationId.ToString());Add(cmd.Parameters,"$a",o.AttemptCount);Add(cmd.Parameters,"$n",(o.NextAttemptAt??DateTimeOffset.UtcNow).ToString("O"));Add(cmd.Parameters,"$s",o.State.ToString());Add(cmd.Parameters,"$e",o.LastError);await cmd.ExecuteNonQueryAsync(ct);}
    public async Task<int> PendingCountAsync(CancellationToken ct=default){await using var c=Open();await using var cmd=c.CreateCommand("SELECT COUNT(*) FROM pending_operations WHERE state <> 'Completed'");return Convert.ToInt32(await cmd.ExecuteScalarAsync(ct));}
    public async Task SaveSettingAsync(string k,string v,CancellationToken ct=default){await using var c=Open();await using var cmd=c.CreateCommand("INSERT INTO settings VALUES($k,$v) ON CONFLICT(key) DO UPDATE SET value=$v");Add(cmd.Parameters,"$k",k);Add(cmd.Parameters,"$v",v);await cmd.ExecuteNonQueryAsync(ct);}
    public async Task<string?> GetSettingAsync(string k,CancellationToken ct=default){await using var c=Open();await using var cmd=c.CreateCommand("SELECT value FROM settings WHERE key=$k");Add(cmd.Parameters,"$k",k);return await cmd.ExecuteScalarAsync(ct) as string;}
}
