using Microsoft.Data.Sqlite;
namespace OrynoSync.Core;
public interface ITransferSessionStore { Task<Guid?> GetAsync(string key, CancellationToken ct = default); Task SaveAsync(string key, Guid uploadId, long expectedSize, string expectedHash, Guid? mappingId = null, CancellationToken ct = default); Task RemoveAsync(string key, CancellationToken ct = default); Task RemoveForMappingAsync(Guid mappingId, CancellationToken ct = default); }
public sealed class SqliteTransferSessionStore(string databasePath) : ITransferSessionStore
{
    private readonly string _path = databasePath; private SqliteConnection Open() { Directory.CreateDirectory(Path.GetDirectoryName(_path)!); var c = new SqliteConnection(new SqliteConnectionStringBuilder { DataSource = _path, Mode = SqliteOpenMode.ReadWriteCreate }.ToString()); c.Open(); return c; }
    public async Task InitializeAsync(CancellationToken ct = default) { await using var c = Open(); await using var cmd = c.CreateCommand("CREATE TABLE IF NOT EXISTS transfer_sessions(session_key TEXT PRIMARY KEY,upload_id TEXT NOT NULL,expected_size INTEGER NOT NULL,expected_hash TEXT NOT NULL,updated_at TEXT NOT NULL,mapping_id TEXT)"); await cmd.ExecuteNonQueryAsync(ct); try { await using var alter = c.CreateCommand("ALTER TABLE transfer_sessions ADD COLUMN mapping_id TEXT"); await alter.ExecuteNonQueryAsync(ct); } catch (SqliteException e) when (e.SqliteErrorCode == 1 && e.Message.Contains("duplicate column", StringComparison.OrdinalIgnoreCase)) { } }
    public async Task<Guid?> GetAsync(string key, CancellationToken ct = default) { await InitializeAsync(ct); await using var c = Open(); await using var cmd = c.CreateCommand("SELECT upload_id FROM transfer_sessions WHERE session_key=$key"); cmd.Parameters.AddWithValue("$key", key); var value = await cmd.ExecuteScalarAsync(ct); return value is string s && Guid.TryParse(s, out var id) ? id : null; }
    public async Task SaveAsync(string key, Guid uploadId, long expectedSize, string expectedHash, Guid? mappingId = null, CancellationToken ct = default) { await InitializeAsync(ct); await using var c = Open(); await using var cmd = c.CreateCommand("INSERT INTO transfer_sessions(session_key,upload_id,expected_size,expected_hash,updated_at,mapping_id) VALUES($key,$id,$size,$hash,$updated,$mapping) ON CONFLICT(session_key) DO UPDATE SET upload_id=$id,expected_size=$size,expected_hash=$hash,updated_at=$updated,mapping_id=$mapping"); cmd.Parameters.AddWithValue("$key", key); cmd.Parameters.AddWithValue("$id", uploadId.ToString()); cmd.Parameters.AddWithValue("$size", expectedSize); cmd.Parameters.AddWithValue("$hash", expectedHash); cmd.Parameters.AddWithValue("$updated", DateTimeOffset.UtcNow.ToString("O")); cmd.Parameters.AddWithValue("$mapping", mappingId?.ToString() ?? (object)DBNull.Value); await cmd.ExecuteNonQueryAsync(ct); }
    public async Task RemoveAsync(string key, CancellationToken ct = default) { await InitializeAsync(ct); await using var c = Open(); await using var cmd = c.CreateCommand("DELETE FROM transfer_sessions WHERE session_key=$key"); cmd.Parameters.AddWithValue("$key", key); await cmd.ExecuteNonQueryAsync(ct); }
    public async Task RemoveForMappingAsync(Guid mappingId, CancellationToken ct = default) { await InitializeAsync(ct); await using var c = Open(); await using var cmd = c.CreateCommand("DELETE FROM transfer_sessions WHERE mapping_id=$mapping"); cmd.Parameters.AddWithValue("$mapping", mappingId.ToString()); await cmd.ExecuteNonQueryAsync(ct); }
}
