using OrynoSync.Core;
using System.Net;
using System.Net.Http;
using System.Text;

namespace OrynoSync.Tests;

public class CoreTests
{
    private static async Task<SqliteLocalStateStore> Store()
    {
        var path=Path.Combine(Path.GetTempPath(),"oryno-"+Guid.NewGuid()+".db");var store=new SqliteLocalStateStore(path);await store.InitializeAsync();return store;
    }
    [Fact] public async Task QueuePersistsAndCoalesces(){var s=await Store();await s.EnqueueAsync(new(Guid.NewGuid(),OperationType.CreateFile,"A.txt"));await s.EnqueueAsync(new(Guid.NewGuid(),OperationType.UpdateFile,"A.txt"));var q=await s.GetPendingAsync(DateTimeOffset.UtcNow);Assert.Single(q);Assert.Equal(OperationType.UpdateFile,q[0].Type);}
    [Fact] public void IgnoreRulesAreCentralized(){var r=new IgnoreRules();Assert.True(r.IsIgnored("Thumbs.db"));Assert.True(r.IsIgnored("x/Thumbs.db"));Assert.True(r.IsIgnored("~$draft.docx"));Assert.True(r.IsIgnored("~$draft.xlsx"));Assert.True(r.IsIgnored("~$Presentation.pptx"));Assert.True(r.IsIgnored("desktop.ini"));Assert.True(r.IsIgnored("D:/sub/desktop.ini"));Assert.True(r.IsIgnored(".tmp.driveupload"));Assert.True(r.IsIgnored(".tmp.driveupload\\191672"));Assert.True(r.IsIgnored("docs/.tmp.drivedownload/inner/b.bin"));Assert.False(r.IsIgnored("draft.docx"));Assert.False(r.IsIgnored("report.xlsx"));Assert.False(r.IsIgnored(".gitignore"));Assert.False(r.IsIgnored(".env"));Assert.False(r.IsIgnored(".tmpfix.txt"));Assert.False(r.IsIgnored("my.tmp.drive-notes.txt"));Assert.False(r.IsIgnored("local/readme.md"));}
    [Fact] public void IgnoredPathsExcludedFromReconciliationPlan(){var root=Guid.NewGuid();var local=new[]{new DesiredLocalItem("normal.docx",ItemType.File,5,DateTimeOffset.UtcNow,"aaa"),new DesiredLocalItem(".tmp.driveupload/191670",ItemType.File,5,DateTimeOffset.UtcNow,"bbb"),new DesiredLocalItem("~$report.xlsx",ItemType.File,5,DateTimeOffset.UtcNow,"ccc")};var server=new[]{new RemoteItemState(Guid.NewGuid(),root,null,"old.docx","old.docx","file",5,DateTimeOffset.UtcNow,"ddd",1,1,RemotePlanningState.MetadataOnly)};var r=QueueNormalizer.Plan(local,server,[]);Assert.Contains(r.Operations,x=>x.RelativePath=="normal.docx"&&x.Type==OperationType.CreateFile);Assert.DoesNotContain(r.Operations,x=>x.RelativePath.Contains(".tmp.driveupload"));Assert.DoesNotContain(r.Operations,x=>x.RelativePath=="~$report.xlsx");Assert.Empty(r.Conflicts);}
    [Fact] public void IgnoredRemoteNotMaterializedRemotelyLocally(){var root=Guid.NewGuid();var local=new[]{new DesiredLocalItem("keep.txt",ItemType.File,5,DateTimeOffset.UtcNow,"aaa")};var server=new[]{new RemoteItemState(Guid.NewGuid(),root,null,"keep.txt","keep.txt","file",5,DateTimeOffset.UtcNow,"aaa",1,1,RemotePlanningState.MetadataOnly),new RemoteItemState(Guid.NewGuid(),root,null,".tmp.driveupload/remote.bin",".tmp.driveupload/remote.bin","file",5,DateTimeOffset.UtcNow,"abc",1,1,RemotePlanningState.MetadataOnly),new RemoteItemState(Guid.NewGuid(),root,null,"gone.txt","gone.txt","file",5,DateTimeOffset.UtcNow,"abc",1,1,RemotePlanningState.MetadataOnly)};var r=QueueNormalizer.Plan(local,server,[]);Assert.Contains(r.Operations,x=>x.RelativePath=="gone.txt"&&x.Type==OperationType.DownloadFile);Assert.DoesNotContain(r.Operations,x=>x.RelativePath.Contains(".tmp.driveupload"));Assert.DoesNotContain(r.Operations,x=>x.RelativePath=="keep.txt");}
    [Fact] public async Task IgnoredTempFilesNeverEnterQueueAndIgnoredMissingNotDeleted(){var db=Path.Combine(Path.GetTempPath(),"oryno-ignore-"+Guid.NewGuid()+".db");var root=Path.Combine(Path.GetTempPath(),"oryno-ignore-root-"+Guid.NewGuid());Directory.CreateDirectory(Path.Combine(root,".tmp.driveupload"));await File.WriteAllTextAsync(Path.Combine(root,"normal.txt"),"keep");await File.WriteAllTextAsync(Path.Combine(root,".tmp.driveupload","stage.bin"),"stage");await File.WriteAllTextAsync(Path.Combine(root,"~$open.docx"),"x");var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var mapping=NewMapping(root) with { ServerRootId=Guid.NewGuid(), ServerRootName="Prod" };await store.AddMappingAsync(mapping);await store.UpsertItemAsync(new(mapping.MappingId,".tmp.driveupload/stage-old.bin",ItemType.File,3,DateTimeOffset.UtcNow),default);await store.UpsertItemAsync(new(mapping.MappingId,"gone-normal.txt",ItemType.File,3,DateTimeOffset.UtcNow),default);var done=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var manager=new SyncMappingRuntimeManager(store);manager.Progress+=(m,p)=>{if(p.IsComplete)done.TrySetResult();};await manager.StartAsync(mapping);await done.Task.WaitAsync(TimeSpan.FromSeconds(30));manager.Dispose();var pending=await store.GetPendingAsync(mapping.MappingId,DateTimeOffset.MaxValue);var items=await store.GetItemsAsync(mapping.MappingId);Assert.Contains(pending,o=>o.Type==OperationType.CreateFile&&o.RelativePath=="normal.txt");Assert.DoesNotContain(pending,o=>o.RelativePath.Contains(".tmp.driveupload"));Assert.DoesNotContain(pending,o=>o.RelativePath.Contains("~$open.docx"));Assert.Contains(pending,o=>o.Type==OperationType.Delete&&o.RelativePath=="gone-normal.txt");Assert.DoesNotContain(pending,o=>o.RelativePath==".tmp.driveupload/stage-old.bin");Assert.DoesNotContain(items,x=>x.RelativePath.Contains("~$open.docx"));Directory.Delete(root,true);}
    [Fact] public void WindowsNamesAndCaseCollisionsAreDetected(){Assert.False(PathRules.IsWindowsCompatible("CON.txt"));Assert.False(PathRules.IsWindowsCompatible("a."));Assert.True(PathRules.IsCaseCollision(["A.txt","a.txt"]));}
    [Fact] public void ConnectionStateUsesReconnectingBeforeOffline(){var tracker=new ConnectionStateTracker();Assert.Equal(ConnectionState.Connected,tracker.Observe(ConnectionStatus.Connected));Assert.Equal(ConnectionState.Reconnecting,tracker.Observe(ConnectionStatus.ServerUnavailable));Assert.Equal(ConnectionState.Connected,tracker.Observe(ConnectionStatus.Connected));Assert.Equal(ConnectionState.AuthenticationRequired,tracker.Observe(ConnectionStatus.AuthenticationRequired));}
    [Fact] public void UserFacingErrorsNeverExposeRawTransportNames(){Assert.Equal("FILE_LOCKED",UserFacingErrorMapper.Map("sharing violation").Code);Assert.Equal("File is currently being used by another application.",UserFacingErrorMapper.Map("sharing violation").Message);Assert.Equal("AUTHORIZATION_REQUIRED",UserFacingErrorMapper.Map("DEVICE_REVOKED (401)").Code);}
    [Fact] public void SuppressionUsesMetadata(){var s=new LocalMutationSuppression();var p="file.txt";var f=new FileInfo(Path.GetTempFileName());s.Expect(p,f.Length,f.LastWriteTimeUtc);Assert.True(s.IsSuppressed(p,f));Assert.False(s.IsSuppressed(p,f));}
    [Fact] public async Task Blake3UsesStreamingProductionHash(){var path=Path.Combine(Path.GetTempPath(),$"oryno-blake3-{Guid.NewGuid():N}.bin");await File.WriteAllBytesAsync(path,[]);Assert.Equal("af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",await new Blake3ContentHasher().ComputeAsync(path));File.Delete(path);}
    [Fact] public void QueueNormalizationUsesCurrentDesiredState(){var root=Guid.NewGuid();var local=new[]{new DesiredLocalItem("A.txt",ItemType.File,3,DateTimeOffset.UtcNow,"aaa"),new DesiredLocalItem("new.txt",ItemType.File,1,DateTimeOffset.UtcNow,"bbb")};var server=new[]{new RemoteItemState(Guid.NewGuid(),root,null,"A.txt","A.txt","file",3,DateTimeOffset.UtcNow,"aaa",1,1,RemotePlanningState.MetadataOnly),new RemoteItemState(Guid.NewGuid(),root,null,"gone.txt","gone.txt","file",2,DateTimeOffset.UtcNow,"ccc",1,1,RemotePlanningState.MetadataOnly)};var old=new[]{new MappingPendingOperation(Guid.NewGuid(),Guid.NewGuid(),OperationType.CreateFile,"A.txt",null,DateTimeOffset.UtcNow,0,DateTimeOffset.UtcNow,OperationState.Pending,null),new MappingPendingOperation(Guid.NewGuid(),Guid.NewGuid(),OperationType.UpdateFile,"A.txt",null,DateTimeOffset.UtcNow,0,DateTimeOffset.UtcNow,OperationState.Pending,null)};var result=QueueNormalizer.Plan(local,server,old);Assert.Contains(result.Operations,x=>x.Type==OperationType.CreateFile&&x.RelativePath=="new.txt");Assert.Contains(result.Operations,x=>x.Type==OperationType.DownloadFile&&x.RelativePath=="gone.txt");Assert.DoesNotContain(result.Operations,x=>x.RelativePath=="A.txt");Assert.Equal(2,result.OldPendingCount);}
    [Fact] public void QueueNormalizationDetectsBothDifferentAsConflict(){var root=Guid.NewGuid();var local=new[]{new DesiredLocalItem("Report.txt",ItemType.File,3,DateTimeOffset.UtcNow,"local")};var server=new[]{new RemoteItemState(Guid.NewGuid(),root,null,"Report.txt","Report.txt","file",3,DateTimeOffset.UtcNow,"server",2,3,RemotePlanningState.MetadataOnly)};var result=QueueNormalizer.Plan(local,server,[]);Assert.Contains("Report.txt",result.Conflicts);Assert.Empty(result.Operations);}
    [Fact] public async Task ReconciliationCreatesAndRemovesOperations(){var root=Path.Combine(Path.GetTempPath(),"oryno-root-"+Guid.NewGuid());Directory.CreateDirectory(root);var file=Path.Combine(root,"Test.txt");await File.WriteAllTextAsync(file,"hello");var store=await Store();var ops=await new LocalReconciler(store,new IgnoreRules()).ScanAsync(root);Assert.Contains(ops,o=>o.Type==OperationType.CreateFile);File.Delete(file);ops=await new LocalReconciler(store,new IgnoreRules()).ScanAsync(root);Assert.Contains(ops,o=>o.Type==OperationType.Delete);Directory.Delete(root);}
    [Fact] public async Task MockOfflineThenOnline(){var root=Path.Combine(Path.GetTempPath(),"oryno-root-"+Guid.NewGuid());Directory.CreateDirectory(root);var store=await Store();var api=new MockSyncApi{Online=false};await store.EnqueueAsync(new(Guid.NewGuid(),OperationType.CreateFile,"a.txt"));var engine=new SyncEngine(store,api,root);await engine.ProcessQueueAsync();Assert.Equal(EngineState.Offline,engine.State);api.Online=true;await engine.ProcessQueueAsync();Assert.Equal(EngineState.UpToDate,engine.State);Assert.Equal(1,api.SuccessfulOperations);Directory.Delete(root);}
    [Fact] public async Task S1JsonAndBearerContractAreUsed(){var token="secret-bearer";var handler=new RecordingHandler(_=>Response(HttpStatusCode.OK,"[{\"root_id\":\"11111111-1111-1111-1111-111111111111\",\"name\":\"Root\",\"enabled\":true,\"backfill_status\":\"done\",\"anchor_revision\":12}]"));using var http=new HttpClient(new BearerTokenHandler(_=>Task.FromResult<string?>(token)){InnerHandler=handler});var api=new OrynoNasSyncApi(http,new Uri("https://example.test"));var roots=await api.GetSyncRootsAsync();Assert.Single(roots);Assert.Equal("Root",roots[0].Name);Assert.Equal("Bearer secret-bearer",handler.Authorization);Assert.Equal("/api/sync/roots",handler.Path);}
    [Fact] public async Task S1UnauthorizedIsClassified(){var handler=new RecordingHandler(_=>Response(HttpStatusCode.Unauthorized,"{\"ok\":false,\"code\":\"DEVICE_REVOKED\",\"message\":\"device revoked\"}"));using var http=new HttpClient(handler);var api=new OrynoNasSyncApi(http,new Uri("https://example.test"));var result=await api.TestConnectionAsync();Assert.Equal(ConnectionStatus.AuthenticationRevoked,result.Status);Assert.Equal("DEVICE_REVOKED",result.Code);}
    [Fact] public async Task InventoryPaginationUsesAnchorAndPersistsRemoteRows(){var root=Guid.NewGuid();var remote=new RemoteStateStore(Path.Combine(Path.GetTempPath(),"oryno-remote-"+Guid.NewGuid()+".db"));await remote.InitializeAsync();var api=new FakeMetadataApi(root);api.Pages[""]=new(42,[Item("A.txt")],"p2");api.Pages["p2"]=new(42,[Item("B.txt")],null);var coordinator=new MetadataSyncCoordinator(api,remote);await coordinator.RunCycleAsync(root);var state=await remote.GetRootStateAsync(root);Assert.True(state.InventoryComplete);Assert.Equal(42,state.LastRevision);Assert.Equal(2,await remote.CountRemoteItemsAsync(root));Assert.Equal(2,api.InventoryCalls);}
    [Fact] public async Task ChangeFeedAdvancesCursorAndReplayIsIdempotent(){var root=Guid.NewGuid();var db=Path.Combine(Path.GetTempPath(),"oryno-remote-"+Guid.NewGuid()+".db");var local=new SqliteLocalStateStore(db);await local.InitializeAsync();var remote=new RemoteStateStore(db);await remote.InitializeAsync();var api=new FakeMetadataApi(root);api.Pages[""]=new(10,[],null);api.Changes=[new(12,"CREATE",Guid.NewGuid(),1,null,"x.txt","x.txt","file",4,DateTimeOffset.UtcNow,null,"system"),new(15,"UPDATE",Guid.NewGuid(),2,null,"y.txt","y.txt","file",5,DateTimeOffset.UtcNow,null,"system")];var coordinator=new MetadataSyncCoordinator(api,remote);await coordinator.RunCycleAsync(root);var state=await remote.GetRootStateAsync(root);Assert.Equal(15,state.LastRevision);Assert.Equal(2,await remote.CountRemoteItemsAsync(root));await remote.ApplyChangesPageAsync(root,api.Changes,15);Assert.Equal(15,(await remote.GetRootStateAsync(root)).LastRevision);Assert.Equal(2,await remote.CountRemoteItemsAsync(root));}
    [Fact] public async Task CursorExpiredMarksInventoryStaleWithoutTouchingLocalQueue(){var root=Guid.NewGuid();var db=Path.Combine(Path.GetTempPath(),"oryno-remote-"+Guid.NewGuid()+".db");var local=new SqliteLocalStateStore(db);await local.InitializeAsync();await local.EnqueueAsync(new(Guid.NewGuid(),OperationType.UpdateFile,"local.txt"));var remote=new RemoteStateStore(db);await remote.InitializeAsync();var api=new FakeMetadataApi(root){ThrowCursorExpired=true};api.Pages[""]=new(10,[],null);var coordinator=new MetadataSyncCoordinator(api,remote);await coordinator.RunCycleAsync(root);Assert.False((await remote.GetRootStateAsync(root)).InventoryComplete);Assert.Equal(1,await local.PendingCountAsync());}
    [Fact] public async Task CredentialFileDoesNotContainPlaintextToken(){var dir=Path.Combine(Path.GetTempPath(),"oryno-credentials-"+Guid.NewGuid());var store=new WindowsCredentialStore(dir);var token="plain-token-never-in-sqlite";await store.SaveAsync("server",token);var files=Directory.GetFiles(dir);Assert.Single(files);Assert.DoesNotContain(token,Encoding.UTF8.GetString(await File.ReadAllBytesAsync(files[0])));Assert.Equal(token,await store.ReadAsync("server"));}
    [Fact] public void SyncMappingOverlapUsesWindowsCanonicalPaths(){var root=Path.Combine(Path.GetTempPath(),"oryno-map-"+Guid.NewGuid());Assert.True(SyncMappingRules.Overlaps(root,Path.Combine(root,"Projects")));Assert.True(SyncMappingRules.Overlaps(root.ToLowerInvariant(),root));Assert.False(SyncMappingRules.Overlaps(root,root+"-other"));}
    [Fact] public async Task MappingStoreKeepsQueuesIndependent(){var db=Path.Combine(Path.GetTempPath(),"oryno-mappings-"+Guid.NewGuid()+".db");var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var a=NewMapping(Path.Combine(Path.GetTempPath(),"A-"+Guid.NewGuid()));var b=NewMapping(Path.Combine(Path.GetTempPath(),"B-"+Guid.NewGuid()));await store.AddMappingAsync(a);await store.AddMappingAsync(b);await store.EnqueueAsync(new(Guid.NewGuid(),a.MappingId,OperationType.CreateFile,"a.txt",null,DateTimeOffset.UtcNow,0,DateTimeOffset.UtcNow,OperationState.Pending,null));await store.EnqueueAsync(new(Guid.NewGuid(),b.MappingId,OperationType.CreateFile,"b.txt",null,DateTimeOffset.UtcNow,0,DateTimeOffset.UtcNow,OperationState.Pending,null));Assert.Equal(1,await store.PendingCountAsync(a.MappingId));Assert.Equal(1,await store.PendingCountAsync(b.MappingId));}
    [Fact] public async Task DashboardCountsAndFileErrorsPersist(){var db=Path.Combine(Path.GetTempPath(),"oryno-dashboard-"+Guid.NewGuid()+".db");var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var mapping=NewMapping(Path.Combine(Path.GetTempPath(),"dashboard-"+Guid.NewGuid()));await store.AddMappingAsync(mapping);await store.IndexBatchAsync([new(mapping.MappingId,"a.txt",ItemType.File,2,DateTimeOffset.UtcNow)], [new(Guid.NewGuid(),mapping.MappingId,OperationType.UpdateFile,"locked.docx",null,DateTimeOffset.UtcNow,2,DateTimeOffset.UtcNow,OperationState.Failed,"sharing violation")]);var summary=await store.GetDashboardSummaryAsync();Assert.Equal(1,summary.IndexedFiles);Assert.Equal(0,summary.WaitingCount);Assert.Equal(1,summary.ErrorCount);var errors=await store.GetErrorsAsync();Assert.Single(errors);Assert.Equal("File is currently being used by another application.",errors[0].UserMessage);}
    [Fact] public async Task MappingMigrationRetainsLegacyRootItemsAndQueue(){var db=Path.Combine(Path.GetTempPath(),"oryno-migrate-"+Guid.NewGuid()+".db");var legacy=new SqliteLocalStateStore(db);await legacy.InitializeAsync();var root=Path.Combine(Path.GetTempPath(),"oryno-legacy-"+Guid.NewGuid());await legacy.SaveSettingAsync("sync_root",root);await legacy.UpsertItemAsync(new("old.txt",ItemType.File,4,DateTimeOffset.UtcNow));await legacy.EnqueueAsync(new(Guid.NewGuid(),OperationType.UpdateFile,"old.txt"));var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var mappings=await store.GetMappingsAsync();Assert.Single(mappings);Assert.Single(await store.GetItemsAsync(mappings[0].MappingId));Assert.Equal(1,await store.PendingCountAsync(mappings[0].MappingId));}
    [Fact] public async Task MissingMappingRootDoesNotCreateDeleteOperations(){var db=Path.Combine(Path.GetTempPath(),"oryno-unavailable-"+Guid.NewGuid()+".db");var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var mapping=NewMapping(Path.Combine(Path.GetTempPath(),"missing-"+Guid.NewGuid()));await store.AddMappingAsync(mapping);var manager=new SyncMappingRuntimeManager(store);await manager.StartAsync(mapping);var saved=await store.GetMappingAsync(mapping.MappingId);Assert.Equal(MappingStatus.LocalFolderUnavailable,saved!.Status);Assert.Equal(0,await store.PendingCountAsync(mapping.MappingId));}
    [Fact] public async Task MissingRemoteRootDoesNotStartWatcherOrQueueUploads(){var db=Path.Combine(Path.GetTempPath(),"oryno-no-remote-"+Guid.NewGuid()+".db");var root=Path.Combine(Path.GetTempPath(),"oryno-no-remote-root-"+Guid.NewGuid());Directory.CreateDirectory(root);await File.WriteAllTextAsync(Path.Combine(root,"local.txt"),"local");var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var mapping=NewMapping(root) with { ServerRootId=null, ServerRootName=null, Status=MappingStatus.ServerRootUnavailable };await store.AddMappingAsync(mapping);var manager=new SyncMappingRuntimeManager(store);await manager.StartAsync(mapping);await Task.Delay(250);var saved=await store.GetMappingAsync(mapping.MappingId);Assert.Equal(MappingStatus.ServerRootUnavailable,saved!.Status);Assert.Equal(0,await store.PendingCountAsync(mapping.MappingId));Assert.Empty(manager.ActiveMappings);manager.Dispose();Directory.Delete(root,true);}
    [Fact] public async Task MappingScanStartsWithoutBlockingCallerAndReportsProgress(){var db=Path.Combine(Path.GetTempPath(),"oryno-scan-"+Guid.NewGuid()+".db");var root=Path.Combine(Path.GetTempPath(),"oryno-scan-root-"+Guid.NewGuid());Directory.CreateDirectory(root);for(var i=0;i<250;i++)await File.WriteAllTextAsync(Path.Combine(root,$"f-{i:000}.txt"),"data");var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var mapping=NewMapping(root) with { ServerRootId=Guid.NewGuid(), ServerRootName="Prod" };await store.AddMappingAsync(mapping);var progress=new List<ScanProgress>();var done=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var manager=new SyncMappingRuntimeManager(store);manager.Progress+=(m,p)=>{lock(progress)progress.Add(p);if(p.IsComplete)done.TrySetResult();};var started=DateTimeOffset.UtcNow;await manager.StartAsync(mapping);Assert.True((DateTimeOffset.UtcNow-started).TotalSeconds<1);await done.Task.WaitAsync(TimeSpan.FromSeconds(15));Assert.True(progress.Count<80);Assert.Contains(progress,p=>p.FilesFound==250&&p.IsComplete);manager.Dispose();Directory.Delete(root,true);}
    [Fact] public async Task MappingScanHandlesTenThousandFilesInBackground(){var db=Path.Combine(Path.GetTempPath(),"oryno-scan10k-"+Guid.NewGuid()+".db");var root=Path.Combine(Path.GetTempPath(),"oryno-scan10k-root-"+Guid.NewGuid());Directory.CreateDirectory(root);for(var i=0;i<10000;i++)File.WriteAllText(Path.Combine(root,$"f-{i:00000}.txt"),"x");var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var mapping=NewMapping(root) with { ServerRootId=Guid.NewGuid(), ServerRootName="Prod" };await store.AddMappingAsync(mapping);var done=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var manager=new SyncMappingRuntimeManager(store);manager.Progress+=(m,p)=>{if(p.IsComplete&&p.FilesFound==10000)done.TrySetResult();};var started=DateTimeOffset.UtcNow;await manager.StartAsync(mapping);Assert.True((DateTimeOffset.UtcNow-started).TotalSeconds<1);await done.Task.WaitAsync(TimeSpan.FromSeconds(60));Assert.Equal(10000,await store.PendingCountAsync(mapping.MappingId));manager.Dispose();Directory.Delete(root,true);}
    [Fact] public async Task RemoveMappingReleasesRootAndPreservesLocalFiles(){var db=Path.Combine(Path.GetTempPath(),"oryno-remove-"+Guid.NewGuid()+".db");var root=Path.Combine(Path.GetTempPath(),"oryno-remove-root-"+Guid.NewGuid());Directory.CreateDirectory(root);var file=Path.Combine(root,"keep.txt");await File.WriteAllTextAsync(file,"keep");var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var serverRoot=Guid.NewGuid();var mapping=NewMapping(root) with { ServerRootId=serverRoot, ServerRootName="Test" };await store.AddMappingAsync(mapping);await store.EnqueueAsync(new(Guid.NewGuid(),mapping.MappingId,OperationType.UpdateFile,"keep.txt",null,DateTimeOffset.UtcNow,0,DateTimeOffset.UtcNow,OperationState.Pending,null));await store.RemoveMappingAsync(mapping.MappingId);var replacement=NewMapping(root+"-replacement") with { ServerRootId=serverRoot, ServerRootName="Test" };await store.AddMappingAsync(replacement);Assert.True(File.Exists(file));}
    [Fact] public async Task TransferSessionsAreRemovedByMappingOnly(){var db=Path.Combine(Path.GetTempPath(),"oryno-transfer-"+Guid.NewGuid()+".db");var store=new SqliteTransferSessionStore(db);var mapping=Guid.NewGuid();var other=Guid.NewGuid();var key=Guid.NewGuid().ToString();var otherKey=Guid.NewGuid().ToString();await store.SaveAsync(key,Guid.NewGuid(),10,"hash",mapping);await store.SaveAsync(otherKey,Guid.NewGuid(),10,"hash",other);await store.RemoveForMappingAsync(mapping);Assert.Null(await store.GetAsync(key));Assert.NotNull(await store.GetAsync(otherKey));}
    [Fact] public void StatusStateReadyToSyncVisible(){var m=NewMappingWithDest("C:\\Work") with { Status=MappingStatus.ReadyToSync };Assert.Equal(MappingStatus.ReadyToSync,m.Status);Assert.Equal("Dest",m.ServerDestinationRelativePath);}
    [Fact] public void StoppedIsDistinctFromSyncingAndReadyToSync(){var stopped=NewMappingWithDest("C:\\Work") with { Status=MappingStatus.Stopped };var syncing=NewMappingWithDest("C:\\Work") with { Status=MappingStatus.Syncing };var rts=NewMappingWithDest("C:\\Work") with { Status=MappingStatus.ReadyToSync };Assert.Equal(MappingStatus.Stopped,stopped.Status);Assert.NotEqual(MappingStatus.Syncing,stopped.Status);Assert.NotEqual(MappingStatus.ReadyToSync,stopped.Status);Assert.NotEqual(stopped.Status,syncing.Status);Assert.NotEqual(stopped.Status,rts.Status);}
    [Fact] public async Task ChooseDestinationSetsStoppedStatus(){var db=Path.Combine(Path.GetTempPath(),"oryno-dest-stopped-"+Guid.NewGuid()+".db");var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var m=NewMappingWithDest("C:\\Work") with { ServerRootId=Guid.NewGuid(), Status=MappingStatus.Stopped };await store.AddMappingAsync(m);var saved=await store.GetMappingAsync(m.MappingId);Assert.Equal(MappingStatus.Stopped,saved!.Status);}
    [Fact] public void ReadyToSyncIsDistinctFromSyncing(){var m=NewMappingWithDest("C:\\Work") with { Status=MappingStatus.ReadyToSync };Assert.Equal(MappingStatus.ReadyToSync,m.Status);Assert.NotEqual(MappingStatus.Syncing,m.Status);Assert.NotEqual(MappingStatus.Scanning,m.Status);}
    [Fact] public async Task StartSyncTransitionsFromReadyToSync(){var db=Path.Combine(Path.GetTempPath(),"oryno-startsync-"+Guid.NewGuid()+".db");var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var mapping=NewMappingWithDest("C:\\Work") with { ServerRootId=Guid.NewGuid(), Status=MappingStatus.ReadyToSync };await store.AddMappingAsync(mapping);var rt=new SyncMappingRuntimeManager(store);await rt.StartSyncAsync(mapping);var saved=await store.GetMappingAsync(mapping.MappingId);Assert.True(saved!.Status==MappingStatus.Syncing||saved.Status==MappingStatus.Scanning);}
    [Fact] public async Task StartAfterStopRequeuesWaitingChanges(){var db=Path.Combine(Path.GetTempPath(),"oryno-start-stop-"+Guid.NewGuid()+".db");var root=Path.Combine(Path.GetTempPath(),"oryno-ss-root-"+Guid.NewGuid());Directory.CreateDirectory(root);await File.WriteAllTextAsync(Path.Combine(root,"new.txt"),"hi");var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var mapping=NewMapping(root) with { ServerRootId=Guid.NewGuid(), Status=MappingStatus.Stopped };await store.AddMappingAsync(mapping);var rt=new SyncMappingRuntimeManager(store);await rt.StartAsync(mapping);await Task.Delay(500);var pending=await store.GetPendingAsync(mapping.MappingId,DateTimeOffset.UtcNow);Assert.Contains(pending,o=>o.RelativePath=="new.txt");rt.Dispose();Directory.Delete(root,true);}
    [Fact] public async Task DestinationChangeInvalidatesPlanButPreservesFiles(){var db=Path.Combine(Path.GetTempPath(),"oryno-destchg-"+Guid.NewGuid()+".db");var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var m=NewMappingWithDest("C:\\Work") with { ServerRootId=Guid.NewGuid(), ServerRootName="Root" };await store.AddMappingAsync(m);await store.EnqueueAsync(new(Guid.NewGuid(),m.MappingId,OperationType.CreateFile,"a.txt",null,DateTimeOffset.UtcNow,0,DateTimeOffset.UtcNow,OperationState.Pending,null));var m2=m with { ServerDestinationRelativePath="Documents" };await store.UpdateMappingAsync(m2);var pending=await store.GetPendingAsync(m.MappingId,DateTimeOffset.UtcNow);Assert.NotNull(m2.ServerDestinationRelativePath);}
    private static SyncMapping NewMapping(string path)=>new(Guid.NewGuid(),path,null,null,true,DateTimeOffset.UtcNow,DateTimeOffset.UtcNow,null,"NotStarted",null,null,MappingStatus.Offline);
    private static SyncMapping NewMappingWithDest(string path)=>new(Guid.NewGuid(),path,null,null,true,DateTimeOffset.UtcNow,DateTimeOffset.UtcNow,null,"NotStarted",null,null,MappingStatus.ReadyToSync,Guid.NewGuid(),"Dest");
    private static HttpResponseMessage Response(HttpStatusCode status,string body){return new HttpResponseMessage(status){Content=new StringContent(body,Encoding.UTF8,"application/json")};}
    [Fact] public void LocalDeleteIntentPlansDeleteNotDownload(){var root=Guid.NewGuid();var mid=Guid.NewGuid();var server=new[]{new RemoteItemState(Guid.NewGuid(),root,null,"gone.txt","gone.txt","file",5,DateTimeOffset.UtcNow,"abc",1,1,RemotePlanningState.MetadataOnly)};var tracked=new Dictionary<string,MappingLocalItem>(StringComparer.OrdinalIgnoreCase){["gone.txt"]=new(mid,"gone.txt",ItemType.File,5,DateTimeOffset.UtcNow,SyncItemState.DeletedLocal)};var r=QueueNormalizer.Plan([],server,[],tracked);Assert.Contains(r.Operations,x=>x.RelativePath=="gone.txt"&&x.Type==OperationType.Delete);Assert.DoesNotContain(r.Operations,x=>x.Type==OperationType.DownloadFile);}
    [Fact] public void WithoutDeleteIntentRemoteOnlyIsDownloaded(){var root=Guid.NewGuid();var server=new[]{new RemoteItemState(Guid.NewGuid(),root,null,"fresh.txt","fresh.txt","file",5,DateTimeOffset.UtcNow,"abc",1,1,RemotePlanningState.MetadataOnly)};var r=QueueNormalizer.Plan([],server,[]);Assert.Contains(r.Operations,x=>x.RelativePath=="fresh.txt"&&x.Type==OperationType.DownloadFile);}

    private static RemoteItemDto Item(string name)=>new(Guid.NewGuid(),null,name,name,"file",4,DateTimeOffset.UtcNow,null,1);
    private sealed class RecordingHandler(Func<HttpRequestMessage,HttpResponseMessage> response):HttpMessageHandler{public string? Authorization;public string? Path;protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken ct){Authorization=request.Headers.Authorization?.ToString();Path=request.RequestUri?.AbsolutePath;var r=response(request);r.RequestMessage=request;return Task.FromResult(r);}}
    // §4 regression: сервер без HEAD отвечал 405 → клиент не получал авторитетный хэш,
    // объявлял ложный конфликт и плодил conflict-копии. Проверяем fallback на ranged GET.
    [Fact] public async Task ContentMetadataFallsBackToRangeGetWhenHeadUnsupported()
    {
        var headCalls=0; var getCalls=0;
        var handler=new RecordingHandler(req=>
        {
            if(req.Method==HttpMethod.Head){headCalls++;return new HttpResponseMessage(HttpStatusCode.MethodNotAllowed);}
            getCalls++;
            var r=new HttpResponseMessage(HttpStatusCode.PartialContent){Content=new ByteArrayContent(new byte[]{0})};
            r.Content.Headers.ContentRange=new System.Net.Http.Headers.ContentRangeHeaderValue(0,0,63);
            r.Headers.Add("X-Sync-Content-Hash","deadbeef");
            r.Headers.Add("X-Sync-Mtime","2026-09-17T02:00:00+00:00");
            return r;
        });
        using var http=new HttpClient(handler);
        var api=new OrynoNasSyncApi(http,new Uri("https://example.test"));
        var meta=await api.GetContentMetadataAsync(Guid.NewGuid(),7);
        Assert.Equal(63,meta.Size);
        Assert.Equal("deadbeef",meta.Hash);
        Assert.NotNull(meta.Mtime);
        Assert.Equal(1,headCalls);
        Assert.Equal(1,getCalls);
    }
    [Fact] public async Task ContentMetadataUsesHeadWhenServerSupportsIt()
    {
        string? method=null;
        var handler=new RecordingHandler(req=>{method=req.Method.Method;var r=new HttpResponseMessage(HttpStatusCode.OK){Content=new ByteArrayContent(new byte[5])};r.Headers.Add("X-Sync-Content-Hash","abc123");return r;});
        using var http=new HttpClient(handler);
        var api=new OrynoNasSyncApi(http,new Uri("https://example.test"));
        var meta=await api.GetContentMetadataAsync(Guid.NewGuid(),1);
        Assert.Equal("HEAD",method);
        Assert.Equal(5,meta.Size);
        Assert.Equal("abc123",meta.Hash);
    }

    // §1/§3 regression: инвентарь сервера отдаёт пути со слэшами ("Work/file.txt"), а Scope() — с
    // обратными. Из-за этого DELETE-операция не находила элемент: помечала Completed без HTTP-запроса,
    // файл оставался на NAS и следующий reconcile скачивал его обратно (воскрешение).
    [Fact] public void RemoteIndexNormalizesSeparatorsSoDeleteLookupHits(){
        var root=Guid.NewGuid();
        var mapping=new SyncMapping(Guid.NewGuid(),@"E:\Работа",root,"Oryno NAS",true,DateTimeOffset.UtcNow,DateTimeOffset.UtcNow,1,"Ready",null,null,MappingStatus.Syncing,null,"Работа");
        var items=new[]{new RemoteItemState(Guid.NewGuid(),root,null,"oryno-delete-proof-v2.txt","Работа/oryno-delete-proof-v2.txt","file",41,DateTimeOffset.UtcNow,"9fe5993b",1,1,RemotePlanningState.MetadataOnly)};
        var index=MappingTransferCoordinator.IndexRemoteItems(items);
        var scoped=mapping.Scope("oryno-delete-proof-v2.txt");
        Assert.True(index.ContainsKey(scoped),$"expected {scoped} in [{string.Join(",",index.Keys)}]");}

    // §1/§3 regression: хранилище может содержать оба написания одного пути — индекс не должен падать.
    [Fact] public void RemoteIndexDeduplicatesBothSpellings(){
        var root=Guid.NewGuid();
        var items=new[]{
            new RemoteItemState(Guid.NewGuid(),root,null,"a.txt","Work/a.txt","file",1,DateTimeOffset.UtcNow,"h1",1,1,RemotePlanningState.MetadataOnly),
            new RemoteItemState(Guid.NewGuid(),root,null,"a.txt",@"Work\a.txt","file",1,DateTimeOffset.UtcNow,"h2",1,1,RemotePlanningState.MetadataOnly)};
        var index=MappingTransferCoordinator.IndexRemoteItems(items);
        Assert.Single(index);Assert.Equal(@"Work\a.txt",index.Keys.First());}

    private sealed class FakeMetadataApi(Guid root):ISyncMetadataApi{public readonly Dictionary<string,InventoryPageDto> Pages=[];public List<RemoteChangeDto> Changes=[];public int InventoryCalls;public bool ThrowCursorExpired;public SyncCapabilities Capabilities=>SyncCapabilities.MetadataSync|SyncCapabilities.ChangeFeed;public Task<ConnectionResult> TestConnectionAsync(CancellationToken ct=default)=>Task.FromResult(new ConnectionResult(ConnectionStatus.Connected));public Task<IReadOnlyList<SyncRootDto>> GetSyncRootsAsync(CancellationToken ct=default)=>Task.FromResult<IReadOnlyList<SyncRootDto>>([new(root,"Root",true,"done",42)]);public Task<InventoryPageDto> GetInventoryPageAsync(Guid rootId,string? cursor,int limit,CancellationToken ct=default){InventoryCalls++;return Task.FromResult(Pages[cursor??""]);}public Task<ChangesPageDto> GetChangesPageAsync(Guid rootId,long after,int limit,CancellationToken ct=default){if(ThrowCursorExpired)return Task.FromException<ChangesPageDto>(new SyncApiException(HttpStatusCode.Gone,"SYNC_CURSOR_EXPIRED","expired"));var page=Changes.Where(x=>x.Revision>after).ToArray();return Task.FromResult(new ChangesPageDto(page,page.Length==0?after:page[^1].Revision,false));}}
}
