using OrynoSync.Core;
using System.Net;
using System.Net.Http;
using System.Text;

namespace OrynoSync.Tests;

public class CoreTests
{
    private static async Task<SqliteLocalStateStore> Store()
    {
        var path=Path.Combine(Path.GetTempPath(),"oryno-"+Guid.NewGuid()+".db");var store=new SqliteLocalStateStore(path);await store.InitializeAsync();return store;
    }
    [Fact] public async Task QueuePersistsAndCoalesces(){var s=await Store();await s.EnqueueAsync(new(Guid.NewGuid(),OperationType.CreateFile,"A.txt"));await s.EnqueueAsync(new(Guid.NewGuid(),OperationType.UpdateFile,"A.txt"));var q=await s.GetPendingAsync(DateTimeOffset.UtcNow);Assert.Single(q);Assert.Equal(OperationType.UpdateFile,q[0].Type);}
    [Fact] public void IgnoreRulesAreCentralized(){var r=new IgnoreRules();Assert.True(r.IsIgnored("x/Thumbs.db"));Assert.True(r.IsIgnored("~$draft.docx"));Assert.False(r.IsIgnored("draft.docx"));}
    [Fact] public void WindowsNamesAndCaseCollisionsAreDetected(){Assert.False(PathRules.IsWindowsCompatible("CON.txt"));Assert.False(PathRules.IsWindowsCompatible("a."));Assert.True(PathRules.IsCaseCollision(["A.txt","a.txt"]));}
    [Fact] public void SuppressionUsesMetadata(){var s=new LocalMutationSuppression();var p="file.txt";var f=new FileInfo(Path.GetTempFileName());s.Expect(p,f.Length,f.LastWriteTimeUtc);Assert.True(s.IsSuppressed(p,f));Assert.False(s.IsSuppressed(p,f));}
    [Fact] public async Task ReconciliationCreatesAndRemovesOperations(){var root=Path.Combine(Path.GetTempPath(),"oryno-root-"+Guid.NewGuid());Directory.CreateDirectory(root);var file=Path.Combine(root,"Test.txt");await File.WriteAllTextAsync(file,"hello");var store=await Store();var ops=await new LocalReconciler(store,new IgnoreRules()).ScanAsync(root);Assert.Contains(ops,o=>o.Type==OperationType.CreateFile);File.Delete(file);ops=await new LocalReconciler(store,new IgnoreRules()).ScanAsync(root);Assert.Contains(ops,o=>o.Type==OperationType.Delete);Directory.Delete(root);}
    [Fact] public async Task MockOfflineThenOnline(){var root=Path.Combine(Path.GetTempPath(),"oryno-root-"+Guid.NewGuid());Directory.CreateDirectory(root);var store=await Store();var api=new MockSyncApi{Online=false};await store.EnqueueAsync(new(Guid.NewGuid(),OperationType.CreateFile,"a.txt"));var engine=new SyncEngine(store,api,root);await engine.ProcessQueueAsync();Assert.Equal(EngineState.Offline,engine.State);api.Online=true;await engine.ProcessQueueAsync();Assert.Equal(EngineState.UpToDate,engine.State);Assert.Equal(1,api.SuccessfulOperations);Directory.Delete(root);}
    [Fact] public async Task S1JsonAndBearerContractAreUsed(){var token="secret-bearer";var handler=new RecordingHandler(_=>Response(HttpStatusCode.OK,"[{\"root_id\":\"11111111-1111-1111-1111-111111111111\",\"name\":\"Root\",\"enabled\":true,\"backfill_status\":\"done\",\"anchor_revision\":12}]"));using var http=new HttpClient(new BearerTokenHandler(_=>Task.FromResult<string?>(token)){InnerHandler=handler});var api=new OrynoNasSyncApi(http,new Uri("https://example.test"));var roots=await api.GetSyncRootsAsync();Assert.Single(roots);Assert.Equal("Root",roots[0].Name);Assert.Equal("Bearer secret-bearer",handler.Authorization);Assert.Equal("/api/sync/roots",handler.Path);}
    [Fact] public async Task S1UnauthorizedIsClassified(){var handler=new RecordingHandler(_=>Response(HttpStatusCode.Unauthorized,"{\"ok\":false,\"code\":\"DEVICE_REVOKED\",\"message\":\"device revoked\"}"));using var http=new HttpClient(handler);var api=new OrynoNasSyncApi(http,new Uri("https://example.test"));var result=await api.TestConnectionAsync();Assert.Equal(ConnectionStatus.AuthenticationRevoked,result.Status);Assert.Equal("DEVICE_REVOKED",result.Code);}
    [Fact] public async Task InventoryPaginationUsesAnchorAndPersistsRemoteRows(){var root=Guid.NewGuid();var remote=new RemoteStateStore(Path.Combine(Path.GetTempPath(),"oryno-remote-"+Guid.NewGuid()+".db"));await remote.InitializeAsync();var api=new FakeMetadataApi(root);api.Pages[""]=new(42,[Item("A.txt")],"p2");api.Pages["p2"]=new(42,[Item("B.txt")],null);var coordinator=new MetadataSyncCoordinator(api,remote);await coordinator.RunCycleAsync(root);var state=await remote.GetRootStateAsync(root);Assert.True(state.InventoryComplete);Assert.Equal(42,state.LastRevision);Assert.Equal(2,await remote.CountRemoteItemsAsync(root));Assert.Equal(2,api.InventoryCalls);}
    [Fact] public async Task ChangeFeedAdvancesCursorAndReplayIsIdempotent(){var root=Guid.NewGuid();var db=Path.Combine(Path.GetTempPath(),"oryno-remote-"+Guid.NewGuid()+".db");var local=new SqliteLocalStateStore(db);await local.InitializeAsync();var remote=new RemoteStateStore(db);await remote.InitializeAsync();var api=new FakeMetadataApi(root);api.Pages[""]=new(10,[],null);api.Changes=[new(12,"CREATE",Guid.NewGuid(),1,null,"x.txt","x.txt","file",4,DateTimeOffset.UtcNow,null,"system"),new(15,"UPDATE",Guid.NewGuid(),2,null,"y.txt","y.txt","file",5,DateTimeOffset.UtcNow,null,"system")];var coordinator=new MetadataSyncCoordinator(api,remote);await coordinator.RunCycleAsync(root);var state=await remote.GetRootStateAsync(root);Assert.Equal(15,state.LastRevision);Assert.Equal(2,await remote.CountRemoteItemsAsync(root));await remote.ApplyChangesPageAsync(root,api.Changes,15);Assert.Equal(15,(await remote.GetRootStateAsync(root)).LastRevision);Assert.Equal(2,await remote.CountRemoteItemsAsync(root));}
    [Fact] public async Task CursorExpiredMarksInventoryStaleWithoutTouchingLocalQueue(){var root=Guid.NewGuid();var db=Path.Combine(Path.GetTempPath(),"oryno-remote-"+Guid.NewGuid()+".db");var local=new SqliteLocalStateStore(db);await local.InitializeAsync();await local.EnqueueAsync(new(Guid.NewGuid(),OperationType.UpdateFile,"local.txt"));var remote=new RemoteStateStore(db);await remote.InitializeAsync();var api=new FakeMetadataApi(root){ThrowCursorExpired=true};api.Pages[""]=new(10,[],null);var coordinator=new MetadataSyncCoordinator(api,remote);await coordinator.RunCycleAsync(root);Assert.False((await remote.GetRootStateAsync(root)).InventoryComplete);Assert.Equal(1,await local.PendingCountAsync());}
    [Fact] public async Task CredentialFileDoesNotContainPlaintextToken(){var dir=Path.Combine(Path.GetTempPath(),"oryno-credentials-"+Guid.NewGuid());var store=new WindowsCredentialStore(dir);var token="plain-token-never-in-sqlite";await store.SaveAsync("server",token);var files=Directory.GetFiles(dir);Assert.Single(files);Assert.DoesNotContain(token,Encoding.UTF8.GetString(await File.ReadAllBytesAsync(files[0])));Assert.Equal(token,await store.ReadAsync("server"));}
    [Fact] public void SyncMappingOverlapUsesWindowsCanonicalPaths(){var root=Path.Combine(Path.GetTempPath(),"oryno-map-"+Guid.NewGuid());Assert.True(SyncMappingRules.Overlaps(root,Path.Combine(root,"Projects")));Assert.True(SyncMappingRules.Overlaps(root.ToLowerInvariant(),root));Assert.False(SyncMappingRules.Overlaps(root,root+"-other"));}
    [Fact] public async Task MappingStoreKeepsQueuesIndependent(){var db=Path.Combine(Path.GetTempPath(),"oryno-mappings-"+Guid.NewGuid()+".db");var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var a=NewMapping(Path.Combine(Path.GetTempPath(),"A-"+Guid.NewGuid()));var b=NewMapping(Path.Combine(Path.GetTempPath(),"B-"+Guid.NewGuid()));await store.AddMappingAsync(a);await store.AddMappingAsync(b);await store.EnqueueAsync(new(Guid.NewGuid(),a.MappingId,OperationType.CreateFile,"a.txt",null,DateTimeOffset.UtcNow,0,DateTimeOffset.UtcNow,OperationState.Pending,null));await store.EnqueueAsync(new(Guid.NewGuid(),b.MappingId,OperationType.CreateFile,"b.txt",null,DateTimeOffset.UtcNow,0,DateTimeOffset.UtcNow,OperationState.Pending,null));Assert.Equal(1,await store.PendingCountAsync(a.MappingId));Assert.Equal(1,await store.PendingCountAsync(b.MappingId));}
    [Fact] public async Task MappingMigrationRetainsLegacyRootItemsAndQueue(){var db=Path.Combine(Path.GetTempPath(),"oryno-migrate-"+Guid.NewGuid()+".db");var legacy=new SqliteLocalStateStore(db);await legacy.InitializeAsync();var root=Path.Combine(Path.GetTempPath(),"oryno-legacy-"+Guid.NewGuid());await legacy.SaveSettingAsync("sync_root",root);await legacy.UpsertItemAsync(new("old.txt",ItemType.File,4,DateTimeOffset.UtcNow));await legacy.EnqueueAsync(new(Guid.NewGuid(),OperationType.UpdateFile,"old.txt"));var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var mappings=await store.GetMappingsAsync();Assert.Single(mappings);Assert.Single(await store.GetItemsAsync(mappings[0].MappingId));Assert.Equal(1,await store.PendingCountAsync(mappings[0].MappingId));}
    [Fact] public async Task MissingMappingRootDoesNotCreateDeleteOperations(){var db=Path.Combine(Path.GetTempPath(),"oryno-unavailable-"+Guid.NewGuid()+".db");var store=new SqliteSyncMappingStore(db);await store.InitializeAsync();var mapping=NewMapping(Path.Combine(Path.GetTempPath(),"missing-"+Guid.NewGuid()));await store.AddMappingAsync(mapping);var manager=new SyncMappingRuntimeManager(store);await manager.StartAsync(mapping);var saved=await store.GetMappingAsync(mapping.MappingId);Assert.Equal(MappingStatus.LocalFolderUnavailable,saved!.Status);Assert.Equal(0,await store.PendingCountAsync(mapping.MappingId));}
    private static SyncMapping NewMapping(string path)=>new(Guid.NewGuid(),path,null,null,true,DateTimeOffset.UtcNow,DateTimeOffset.UtcNow,null,"NotStarted",null,null,MappingStatus.Offline);
    private static HttpResponseMessage Response(HttpStatusCode status,string body){return new HttpResponseMessage(status){Content=new StringContent(body,Encoding.UTF8,"application/json")};}
    private static RemoteItemDto Item(string name)=>new(Guid.NewGuid(),null,name,name,"file",4,DateTimeOffset.UtcNow,null,1);
    private sealed class RecordingHandler(Func<HttpRequestMessage,HttpResponseMessage> response):HttpMessageHandler{public string? Authorization;public string? Path;protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken ct){Authorization=request.Headers.Authorization?.ToString();Path=request.RequestUri?.AbsolutePath;var r=response(request);r.RequestMessage=request;return Task.FromResult(r);}}
    private sealed class FakeMetadataApi(Guid root):ISyncMetadataApi{public readonly Dictionary<string,InventoryPageDto> Pages=[];public List<RemoteChangeDto> Changes=[];public int InventoryCalls;public bool ThrowCursorExpired;public SyncCapabilities Capabilities=>SyncCapabilities.MetadataSync|SyncCapabilities.ChangeFeed;public Task<ConnectionResult> TestConnectionAsync(CancellationToken ct=default)=>Task.FromResult(new ConnectionResult(ConnectionStatus.Connected));public Task<IReadOnlyList<SyncRootDto>> GetSyncRootsAsync(CancellationToken ct=default)=>Task.FromResult<IReadOnlyList<SyncRootDto>>([new(root,"Root",true,"done",42)]);public Task<InventoryPageDto> GetInventoryPageAsync(Guid rootId,string? cursor,int limit,CancellationToken ct=default){InventoryCalls++;return Task.FromResult(Pages[cursor??""]);}public Task<ChangesPageDto> GetChangesPageAsync(Guid rootId,long after,int limit,CancellationToken ct=default){if(ThrowCursorExpired)return Task.FromException<ChangesPageDto>(new SyncApiException(HttpStatusCode.Gone,"SYNC_CURSOR_EXPIRED","expired"));var page=Changes.Where(x=>x.Revision>after).ToArray();return Task.FromResult(new ChangesPageDto(page,page.Length==0?after:page[^1].Revision,false));}}
}
